backend:
  name: github
  repo: maurizio-13a/beyond-the-magic-site
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: simple

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Page HTML", name: "body", widget: "text" }

      - label: "About"
        name: "about"
        file: "about/index.html"
        fields:
          - { label: "Page HTML", name: "body", widget: "text" }

      - label: "Services"
        name: "services"
        file: "services/index.html"
        fields:
          - { label: "Page HTML", name: "body", widget: "text" }

      - label: "Contact"
        name: "contact"
        file: "contact/index.html"
        fields:
          - { label: "Page HTML", name: "body", widget: "text" }
